apiVersion: v1
kind: Service
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
spec:
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
  selector:
    app: rabbitmq
  type: ClusterIP