kind: Deployment
apiVersion: apps/v1
metadata:
  name: threat-detector-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: threat-detector-ui
  template:
    metadata:
      labels:
        app: threat-detector-ui
    spec:
      containers:
        - name: threat-detector-ui
          image: gcr.io/idyllic-kit-269502/threat-detector-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      restartPolicy: Always
