name: Docker Image CI

on:
  push:
    branches: [ master ]
    paths:
      - 'application/App/src/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'application/App/src/**'

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: gpg --version
    - name: Decrypte key file
      run: ./.github/scripts/decrypt_key.sh
      env: 
        PASSPHRASE: ${{ secrets.ENCRYPT_KEY }}
    - name: Authenticate to GCP
      run: gcloud auth activate-service-account --key-file=$HOME/secrets/key.json
    - name: Configure Docker
      run: gcloud auth configure-docker
    - name: Build the Docker image
      run: docker build application/App --file application/App/Dockerfile --tag gcr.io/${{ secrets.PROJECT_ID}}/app:$GITHUB_SHA
    - name: Push the Docker image
      run: docker push gcr.io/${{ secrets.PROJECT_ID}}/app:$GITHUB_SHA
    - name: Set deployment on image
      run: kubectl set image deployment/App App=gcr.io/${{ secrets.PROJECT_ID}}/app:$GITHUB_SHA
