name: Docker Image CI

on:
  pull_request:
    branches:
      - master
      - development
    paths:
      - 'application/threat-detector-ui/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: bash application/threat-detector-ui/runTests.sh || exit 1

  build:
    needs: test
    if: success()

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Decrypte key file
      run: ./.github/scripts/decrypt_key.sh
      env:
        PASSPHRASE: ${{ secrets.ENCRYPT_KEY }}
    - name: Authenticate to GCP
      run: gcloud auth activate-service-account --key-file=$HOME/secrets/key.json
    - name: Set Project
      run: gcloud config set project ${{ secrets.PROJECT_ID}}
    - name: Configure Docker
      run: gcloud auth configure-docker
    - name: setup to cleanup NPM libraries
      run: sudo chown -R $USER ~/.npm
      run: sudo chown -R $USER /usr/lib/node_modules
      run: sudo chown -R $USER /usr/local/lib/node_module

    - name: Install update NPM
      run: npm install -g npm@latest
      working-directory: application/threat-detector-ui
    - name: Remove Node modules
      run: rm -rf node_modules
      working-directory: application/threat-detector-ui
    - name: Install NPM
      run: npm install
      working-directory: application/threat-detector-ui
    - name: NPM build
      run: npm run-script build
      working-directory: application/threat-detector-ui
    - name: Build the Docker image
      run: docker build -t gcr.io/${{ secrets.PROJECT_ID}}/threat-detector-ui:$GITHUB_SHA .
      working-directory: application/threat-detector-ui
    - name: Push the Docker image
      run: docker push gcr.io/${{ secrets.PROJECT_ID}}/threat-detector-ui:$GITHUB_SHA
      working-directory: application/threat-detector-ui
    - name: Configure kubernetes for master
      if: github.base_ref == 'master'
      run: gcloud container clusters get-credentials --zone us-central1-c cluster-1
    - name: Configure kubernetes for development
      if: github.base_ref == 'development'
      run: gcloud container clusters get-credentials --zone us-central1-c cluster-2
    - name: Set deployment on image
      run: kubectl set image deployment/threat-detector-ui threat-detector-ui=gcr.io/${{ secrets.PROJECT_ID}}/threat-detector-ui:$GITHUB_SHA
