name: Docker Image CI

on:
  pull_request:
    branches:
      - master
      - development
    paths:
      - 'application/Collector/src/**'
      - 'application/Collector/Dockerfile'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: bash application/Collector/runTests.sh || exit 1

  build:
    if: success()

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Check if master Branch
      if: github.base_ref == 'master'
      run: CLUSTER='cluster-1'
    - name: Check if development Branch
      if: github.base_ref == 'development'
      run: CLUSTER='cluster-2'
    - name: Decrypte key file
      run: ./.github/scripts/decrypt_key.sh
      env: 
        PASSPHRASE: ${{ secrets.ENCRYPT_KEY }}
    - name: Authenticate to GCP
      run: gcloud auth activate-service-account --key-file=$HOME/secrets/key.json
    - name: Set Porject
      run: gcloud config set project ${{ secrets.PROJECT_ID}}
    - name: Configure Docker
      run: gcloud auth configure-docker
    - name: Build the Docker image
      run: docker build application/App --file application/Collector/Dockerfile --tag gcr.io/${{ secrets.PROJECT_ID}}/collector:$GITHUB_SHA --build-arg APIKEY=${{ secrets.API_KEY }} --build-arg APISECRET=${{ secrets.API_SECRET_KEY }}
    - name: Push the Docker image
      run: docker push gcr.io/${{ secrets.PROJECT_ID}}/collector:$GITHUB_SHA
    - name: Configure kubernetes
      run: gcloud container clusters get-credentials --zone us-central1-c $CLUSTER
    - name: Set deployment on image
      run: kubectl set image deployment/collector collector=gcr.io/${{ secrets.PROJECT_ID}}/collector:$GITHUB_SHA
