name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Decrypte key file
      run: ./.github/scripts/decrypt_key.sh
    - name: Authenticate to GCP
      run: gcloud auth activate-service-account ${{ secrets.GCP_SERVICE_ACCOUNT_NAME }} --key-file=$HOME/secrets/key.json
    - name: Configure Docker
      run: gcloud auth configure-docker
    - name: Build the Docker image
      run: docker build App --file App/Dockerfile --tag gcr.io/${{ secrets.PROJECT_ID}}/app:$GITHUB_SHA
    - name: Push the Docker image
      run: docker push gcr.io/${{ secrets.PROJECT_ID}}/app:$GITHUB_SHA
    - name: Set deployment on image
      run: kubectl set image deployment/App App=gcr.io/${{ secrets.PROJECT_ID}}/app:$GITHUB_SHA
